platform :ios, '9.0'

use_frameworks!

target 'MapsAPI_Example' do
  pod 'Cordova', podspec: 'Cordova.podspec.json'
  pod 'MapsAPI', path: '../'

  target 'MapsAPI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
